name: ".github/workflows/main.yml"

on:
  push:
    branches:
      - main
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
      - name: Install and Build
        run: |
          npm install
          npm run build
        run: npm test

      - name: Deploy application
        env:
          API_KEY: ${{secrets.API_KEY}}
        run: npm run deploy

      - name: Reference CONTRIBUTING.md
        run: |\n          npm run lint\n          npm run test:coverage\n
          cat static/bootstrap-select/CONTRIBUTING.md
